[options]
work_mode = "sys"
min_cfg_version="2.4"
library = "WebKit2WebExtension"
version = "4.0"
single_version_file = "."
girs_dir = "../gir-files"
target_path = "."

external_libraries = [
   "Gio",
   "GLib",
   "GObject",
   "Gtk",
   "Soup",
]

[external_libraries]
javascriptcore = "JavaScriptCore"

